version: '2.2'
services:
  client:
    depends_on:
      - server
    build: 
      context: ./banking-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /user/node_modules
    restart: on-failure
    container_name: client

  server:
    depends_on:
      - mongo
    build: 
      -context: ./banking-system-node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /usr/node_modules
    restart: on-failure
    container_name: server
    env_file:
      - ./server/.env

  mongo:
    image: mongo
    restart: on-failure
    container_name: mongo-db
    ports:
      - "27018:27017"
    volumes:
      - ./db-service/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db-service/mongo:/data/db